# Generated by Django 2.1.5 on 2019-01-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
