# Generated by Django 2.1 on 2019-03-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20190317_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='defaultPass', max_length=1024),
        ),
    ]
