# Generated by Django 2.1 on 2019-03-18 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_authenticator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticator',
            old_name='user_id',
            new_name='user',
        ),
    ]
