# Generated by Django 2.1 on 2019-04-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_auto_20190318_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticator',
            old_name='user',
            new_name='usr',
        ),
    ]
