# Generated by Django 2.1 on 2019-04-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_auto_20190402_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticator',
            old_name='usr',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
