# Generated by Django 2.1 on 2019-04-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0007_auto_20190402_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticator',
            old_name='user',
            new_name='usr',
        ),
    ]
