# Generated by Django 2.1 on 2019-04-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0008_auto_20190402_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticator',
            old_name='usr',
            new_name='user',
        ),
    ]
