language: python 

services: 
    - docker

before_install:
    - docker -v
    - sudo /etc/init.d/postgresql stop

install:
    - sudo docker-compose -v 
    - sudo docker-compose -f docker-compose-travis.yml up -d --build 
    - sleep 10s
