services: 
  - docker

before_install:
  - docker -v
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop

install:
  # Start the docker stuff
  - docker-compose build 
  - docker-compose up -d
  - sleep 10

script:
  # Run tests
  - docker-compose exec models sh -c "/app/bazaar/manage.py test"
  - docker-compose exec exp sh -c "/app/experience/manage.py test"
