services: 
    - docker

before_install:
    - docker -v
    - sudo /etc/init.d/postgresql stop

install:
    - sudo docker-compose -v 
    - sudo docker-compose -f docker-compose-travis.yml up -d
    - sleep 10
