version: '3'

services:
  web:
    build: ./src 
    volumes:
      - ./src/:/code
    ports:
      - "8000:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory /code --reload-on-changes /code/bazaar/bazaar/wsgi.py"
