models:
  image: tp33/django
  external_links:
    - mysql:db
  volumes:
    - ./src/bazaar:/app/bazaar
  ports:
    - "8001:8000"
  command: bash -c "chmod 777 -R /app && cd bazaar && mod_wsgi-express start-server --working-directory /app/bazaar --reload-on-changes /app/bazaar/bazaar/wsgi.py"
