models:
  image: tp33/django
  external_links:
    - mysql:db
  volumes:
    - ./src/:/app
  ports:
    - "8000:8000"
  command: bash -c "mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/bazaar/bazaar/wsgi.py"
