models:
  image: tp33/django
  container_name: models
  external_links:
    - mysql:db
  ports:
    - "8001:8000"
  volumes:
    - ./src/bazaar:/app/bazaar
  command: bash -c "chmod +x /app/bazaar/setup.sh && /app/bazaar/setup.sh" 
exp:
  image: tp33/django
  container_name: exp
  links:
    - models:models-api
  ports:
    - "8002:8000"
  volumes:
    - ./src/bazaar:/app/bazaar
  command: bash -c "chmod +x /app/bazaar/setup.sh && /app/bazaar/setup.sh"
web:
  image: tp33/django
  container_name: web
  links:
    - exp:exp-api
  ports:
    - "8000:8000"
  volumes:
    - ./src/bazaar:/app/bazaar
  command: bash -c "chmod +x /app/bazaar/setup.sh && /app/bazaar/setup.sh"