# Generated by Django 2.1 on 2019-02-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_auto_20190205_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
