# Generated by Django 2.1 on 2019-04-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Lifestyle', 'Live a better life'), ('IT Consultation', 'Help with IT problems'), ('Events', 'Help with events'), ('Tutoring', 'Learn something new'), ('Art', 'Get creative'), ('Household', 'Improve your home'), ('Labor', 'Get a hand'), ('Other', 'Anything else')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='preferred_contact',
            field=models.CharField(choices=[('Email', 'Through email'), ('Phone', 'Through phone')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='request_type',
            field=models.CharField(choices=[('Offering', 'Offering service'), ('Asking', 'Asking for service')], max_length=30),
        ),
    ]
