# Generated by Django 2.1.5 on 2019-01-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=900)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField()),
                ('category', models.CharField(choices=[('LI', 'Lifestyle'), ('IT', 'IT Consultation'), ('EV', 'Events'), ('TU', 'Tutoring'), ('AR', 'Art'), ('HO', 'Household'), ('LB', 'Labor'), ('OT', 'Other')], max_length=3)),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
