# Generated by Django 2.1.5 on 2019-02-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preferred_contact',
            field=models.CharField(choices=[('EM', 'Email'), ('PH', 'Phone')], default='PH', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='request_type',
            field=models.CharField(choices=[('OF', 'Offering'), ('AS', 'Asking')], default='SE', max_length=2),
            preserve_default=False,
        ),
    ]
