# Generated by Django 2.1.5 on 2019-02-04 07:59

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20190204_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
